let options = {
    search: null,
    selected: [],
    headers: [
        { text: "TIME-IN", align: "center", value: "timeIn", sortable: true, },
        { text: "TIME-OUT", align: "center", value: "timeOut", sortable: true, },
        { text: "DATE", value: "date", sortable: true },
        { text: "EMPLOYEE", value: "employee", sortable: true },
        { text: "DEPARTMENT", value: "department", sortable: true },
        { text: "", value: "actions", sortable: false }
    ],
    data: [
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
        {
            emotionIn: 5,
            timeIn: "7:30 am",
            emotionOut: 5,
            timeOut: "7:30 am",
            date: "January 6, 2020",
            employee: "Dolores, Lorem Ipsum",
            department: "Faculty",
        },
    ]
}

export default options